### ISSUE TITLE
Tweet's sender page loaded after closing a tweet

### ISSUE THREAD

**Issue by mben42** [ZusorCode/GoodTwitter#19]
Hi,

Unless the old Twitter, when I open a tweet in current tab, the sender's account page is loaded instead of comming back on the page visited before opening the tweet. If the page was the sender's account page, it is reloaded, and therefore scrolling is reset to the top of the page.

Tested on both Firefox and Chrome: same issue.

Steps to reproduce: open and close a tweet in a tab.

Thanks in advance,

**Comment by ZusorCode** [comment]
This is fixed by logging out and back in

**Comment by mben42** [comment]
Reopening the issue, this is not a fix.

**Comment by ZusorCode** [comment]
This has usually worked for other people. If you're still having issues please wait a day or 2, version 2.1 is currently rolling out and has a change that fixes a bunch of bugs that were being caused by the user agent. If the issue persists after clearing cookies in v2.1 I can look into it

**Comment by TheRetroShepherd** [comment]
I'm having this issue as well. I had actually managed to fix it thanks to a reddit post, but Chrome updated and now this exact issue is back again. Logging in and out didn't work, deleting my cookies didn't work, restarting either Chrome or my PC didn't work, reinstalling GoodTwitter itself didn't work, and neither did doing any of these in order. I noticed however that the redirect bug only happened when I was logged into my account, when I logged out twitter worked fine.
